services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USR}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet
  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USR}", "-p${MYSQL_PWD}"]
      timeout: 20s
      retries: 5
      interval: 5s
      start_period: 30s

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_APP: "game:create_app()"
      APP_PROFILE: dev
      FLASK_DEBUG: 1
      FLASK_RUN_EXTRA_FILES: "game/templates/**/*:game/static/**/*:game/ui/**/*"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - appnet
    command: >
      sh -c "flask run --host=0.0.0.0 --reload --extra-files game/templates:game/static:game/ui"

volumes:
  db_data:

networks:
  appnet:
